
// Firebase config object. Code autogenerated by Firebase console at
// Project settings > General > Web app > SDK setup & configuration.
// https://firebase.google.com/docs/web/setup#config-objectConfig

const firebaseConfig = {
  apiKey: "AIzaSyBz8Rsnm1B3l5beoJnrBXjt51tbighCaF8",
  authDomain: "komunitin-project.firebaseapp.com",
  projectId: "komunitin-project",
  storageBucket: "komunitin-project.appspot.com",
  messagingSenderId: "990869913594",
  appId: "1:990869913594:web:2e38aa78fe6d27c8986e43",
  measurementId: "G-RYZMRW1QKC"
};

export default firebaseConfig;
